MAKE := make --no-print-directory

all:
	@$(MAKE) -f makefile_g200ms_debug clean
	@$(MAKE) -f makefile_g200ms_debug
	@$(MAKE) -f makefile_g200ms_release clean
	@$(MAKE) -f makefile_g200ms_release
	